package com.tuxing.sdk.db.dao.upload;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tuxing.sdk.db.entity.AttendanceRecord;

import com.tuxing.sdk.db.dao.upload.AttendanceRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attendanceRecordDaoConfig;

    private final AttendanceRecordDao attendanceRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attendanceRecordDaoConfig = daoConfigMap.get(AttendanceRecordDao.class).clone();
        attendanceRecordDaoConfig.initIdentityScope(type);

        attendanceRecordDao = new AttendanceRecordDao(attendanceRecordDaoConfig, this);

        registerDao(AttendanceRecord.class, attendanceRecordDao);
    }
    
    public void clear() {
        attendanceRecordDaoConfig.getIdentityScope().clear();
    }

    public AttendanceRecordDao getAttendanceRecordDao() {
        return attendanceRecordDao;
    }

}
