package com.tuxing.sdk.db.dao.user;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.tuxing.sdk.db.entity.Game_Score;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table Game_Score.
*/
public class Game_ScoreDao extends AbstractDao<Game_Score, Long> {

    public static final String TABLENAME = "Game_Score";

    /**
     * Properties of entity Game_Score.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property GameName = new Property(1, String.class, "gameName", false, "GAME_NAME");
        public final static Property Score = new Property(2, Integer.class, "score", false, "SCORE");
        public final static Property BestLevel = new Property(3, Integer.class, "bestLevel", false, "BEST_LEVEL");
        public final static Property Percentage = new Property(4, Double.class, "percentage", false, "PERCENTAGE");
        public final static Property Color = new Property(5, String.class, "color", false, "COLOR");
    };


    public Game_ScoreDao(DaoConfig config) {
        super(config);
    }
    
    public Game_ScoreDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'Game_Score' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'GAME_NAME' TEXT," + // 1: gameName
                "'SCORE' INTEGER," + // 2: score
                "'BEST_LEVEL' INTEGER," + // 3: bestLevel
                "'PERCENTAGE' REAL," + // 4: percentage
                "'COLOR' TEXT);"); // 5: color
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'Game_Score'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Game_Score entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String gameName = entity.getGameName();
        if (gameName != null) {
            stmt.bindString(2, gameName);
        }
 
        Integer score = entity.getScore();
        if (score != null) {
            stmt.bindLong(3, score);
        }
 
        Integer bestLevel = entity.getBestLevel();
        if (bestLevel != null) {
            stmt.bindLong(4, bestLevel);
        }
 
        Double percentage = entity.getPercentage();
        if (percentage != null) {
            stmt.bindDouble(5, percentage);
        }
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(6, color);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Game_Score readEntity(Cursor cursor, int offset) {
        Game_Score entity = new Game_Score( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // gameName
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // score
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // bestLevel
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // percentage
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // color
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Game_Score entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGameName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setScore(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setBestLevel(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setPercentage(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setColor(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Game_Score entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Game_Score entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
