package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table AbilityPoint.
 */
public class AbilityPoint implements java.io.Serializable {

    private Long id;
    private Integer number;
    private Integer score;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AbilityPoint() {
    }

    public AbilityPoint(Long id) {
        this.id = id;
    }

    public AbilityPoint(Long id, Integer number, Integer score) {
        this.id = id;
        this.number = number;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
