package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table AbilityDetailList.
 */
public class AbilityDetailList implements java.io.Serializable {

    private Long id;
    private Integer ability;
    private Integer level;
    private Integer avgLevel;
    private Double percentage;
    private Integer score;
    private Integer maxScore;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AbilityDetailList() {
    }

    public AbilityDetailList(Long id) {
        this.id = id;
    }

    public AbilityDetailList(Long id, Integer ability, Integer level, Integer avgLevel, Double percentage, Integer score, Integer maxScore) {
        this.id = id;
        this.ability = ability;
        this.level = level;
        this.avgLevel = avgLevel;
        this.percentage = percentage;
        this.score = score;
        this.maxScore = maxScore;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAbility() {
        return ability;
    }

    public void setAbility(Integer ability) {
        this.ability = ability;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getAvgLevel() {
        return avgLevel;
    }

    public void setAvgLevel(Integer avgLevel) {
        this.avgLevel = avgLevel;
    }

    public Double getPercentage() {
        return percentage;
    }

    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getMaxScore() {
        return maxScore;
    }

    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
