package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table comment.
 */
public class Comment implements java.io.Serializable {

    private Long id;
    private long commentId;
    private Integer commentType;
    private long topicId;
    private Long topicUserId;
    private Integer targetType;
    private Long replayToUserId;
    private String replayToUserName;
    private Long senderId;
    private String senderName;
    private String senderAvatar;
    private Long sendTime;
    private String content;

    // KEEP FIELDS - put your custom fields here

    private  com.tuxing.rpc.proto.UserType userType;
    private String userTitle;
    Feed feed;
    // KEEP FIELDS END

    public Comment() {
    }

    public Comment(Long id) {
        this.id = id;
    }

    public Comment(Long id, long commentId, Integer commentType, long topicId, Long topicUserId, Integer targetType, Long replayToUserId, String replayToUserName, Long senderId, String senderName, String senderAvatar, Long sendTime, String content) {
        this.id = id;
        this.commentId = commentId;
        this.commentType = commentType;
        this.topicId = topicId;
        this.topicUserId = topicUserId;
        this.targetType = targetType;
        this.replayToUserId = replayToUserId;
        this.replayToUserName = replayToUserName;
        this.senderId = senderId;
        this.senderName = senderName;
        this.senderAvatar = senderAvatar;
        this.sendTime = sendTime;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getCommentId() {
        return commentId;
    }

    public void setCommentId(long commentId) {
        this.commentId = commentId;
    }

    public Integer getCommentType() {
        return commentType;
    }

    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    public long getTopicId() {
        return topicId;
    }

    public void setTopicId(long topicId) {
        this.topicId = topicId;
    }

    public Long getTopicUserId() {
        return topicUserId;
    }

    public void setTopicUserId(Long topicUserId) {
        this.topicUserId = topicUserId;
    }

    public Integer getTargetType() {
        return targetType;
    }

    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    public Long getReplayToUserId() {
        return replayToUserId;
    }

    public void setReplayToUserId(Long replayToUserId) {
        this.replayToUserId = replayToUserId;
    }

    public String getReplayToUserName() {
        return replayToUserName;
    }

    public void setReplayToUserName(String replayToUserName) {
        this.replayToUserName = replayToUserName;
    }

    public Long getSenderId() {
        return senderId;
    }

    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    public String getSenderName() {
        return senderName;
    }

    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public String getSenderAvatar() {
        return senderAvatar;
    }

    public void setSenderAvatar(String senderAvatar) {
        this.senderAvatar = senderAvatar;
    }

    public Long getSendTime() {
        return sendTime;
    }

    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    // KEEP METHODS - put your custom methods here

    public com.tuxing.rpc.proto.UserType getUserType() {
        return userType;
    }

    public void setUserType(com.tuxing.rpc.proto.UserType userType) {
        this.userType = userType;
    }

    public String getUserTitle() {
        return userTitle;
    }

    public void setUserTitle(String userTitle) {
        this.userTitle = userTitle;
    }

    public Feed getFeed() {
        return feed;
    }

    public void setFeed(Feed feed) {
        this.feed = feed;
    }
    // KEEP METHODS END

}
