package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table content_item.
 */
public class ContentItem implements java.io.Serializable {

    private Long id;
    private long itemId;
    private Long groupId;
    private String title;
    private String summary;
    private String coverImageUrl;
    private Long publishTime;
    private Integer contentType;
    private String postUrl;
    private String content;

    // KEEP FIELDS - put your custom fields here
    private String html;
    // KEEP FIELDS END

    public ContentItem() {
    }

    public ContentItem(Long id) {
        this.id = id;
    }

    public ContentItem(Long id, long itemId, Long groupId, String title, String summary, String coverImageUrl, Long publishTime, Integer contentType, String postUrl, String content) {
        this.id = id;
        this.itemId = itemId;
        this.groupId = groupId;
        this.title = title;
        this.summary = summary;
        this.coverImageUrl = coverImageUrl;
        this.publishTime = publishTime;
        this.contentType = contentType;
        this.postUrl = postUrl;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getItemId() {
        return itemId;
    }

    public void setItemId(long itemId) {
        this.itemId = itemId;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getCoverImageUrl() {
        return coverImageUrl;
    }

    public void setCoverImageUrl(String coverImageUrl) {
        this.coverImageUrl = coverImageUrl;
    }

    public Long getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    public Integer getContentType() {
        return contentType;
    }

    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    public String getPostUrl() {
        return postUrl;
    }

    public void setPostUrl(String postUrl) {
        this.postUrl = postUrl;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    // KEEP METHODS - put your custom methods here

    public String getHtml() {
        return html;
    }

    public void setHtml(String html) {
        this.html = html;
    }
    // KEEP METHODS END

}
