package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table content_item_group.
 */
public class ContentItemGroup implements java.io.Serializable {

    private Long id;
    private long groupId;

    // KEEP FIELDS - put your custom fields here
    private List<ContentItem> items;
    // KEEP FIELDS END

    public ContentItemGroup() {
    }

    public ContentItemGroup(Long id) {
        this.id = id;
    }

    public ContentItemGroup(Long id, long groupId) {
        this.id = id;
        this.groupId = groupId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getGroupId() {
        return groupId;
    }

    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }

    // KEEP METHODS - put your custom methods here

    public List<ContentItem> getItems() {
        return items;
    }

    public void setItems(List<ContentItem> items) {
        this.items = items;
    }
    // KEEP METHODS END

}
