package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CourseLessonBean.
 */
public class CourseLessonBean implements java.io.Serializable {

    private Long id;
    private Long CourseLessonId;
    private Long createOn;
    private Long updateOn;
    private Long courseId;
    private String title;
    private Long startOn;
    private Long endOn;
    private String videoUrl;
    private Long hits;
    private Long liveHits;
    private Integer liveStatus;
    private String pic;
    private Integer duration;
    private Integer resourceType;
    private String teacherName;
    private String teacherAvatar;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CourseLessonBean() {
    }

    public CourseLessonBean(Long id) {
        this.id = id;
    }

    public CourseLessonBean(Long id, Long CourseLessonId, Long createOn, Long updateOn, Long courseId, String title, Long startOn, Long endOn, String videoUrl, Long hits, Long liveHits, Integer liveStatus, String pic, Integer duration, Integer resourceType, String teacherName, String teacherAvatar) {
        this.id = id;
        this.CourseLessonId = CourseLessonId;
        this.createOn = createOn;
        this.updateOn = updateOn;
        this.courseId = courseId;
        this.title = title;
        this.startOn = startOn;
        this.endOn = endOn;
        this.videoUrl = videoUrl;
        this.hits = hits;
        this.liveHits = liveHits;
        this.liveStatus = liveStatus;
        this.pic = pic;
        this.duration = duration;
        this.resourceType = resourceType;
        this.teacherName = teacherName;
        this.teacherAvatar = teacherAvatar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCourseLessonId() {
        return CourseLessonId;
    }

    public void setCourseLessonId(Long CourseLessonId) {
        this.CourseLessonId = CourseLessonId;
    }

    public Long getCreateOn() {
        return createOn;
    }

    public void setCreateOn(Long createOn) {
        this.createOn = createOn;
    }

    public Long getUpdateOn() {
        return updateOn;
    }

    public void setUpdateOn(Long updateOn) {
        this.updateOn = updateOn;
    }

    public Long getCourseId() {
        return courseId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getStartOn() {
        return startOn;
    }

    public void setStartOn(Long startOn) {
        this.startOn = startOn;
    }

    public Long getEndOn() {
        return endOn;
    }

    public void setEndOn(Long endOn) {
        this.endOn = endOn;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public Long getHits() {
        return hits;
    }

    public void setHits(Long hits) {
        this.hits = hits;
    }

    public Long getLiveHits() {
        return liveHits;
    }

    public void setLiveHits(Long liveHits) {
        this.liveHits = liveHits;
    }

    public Integer getLiveStatus() {
        return liveStatus;
    }

    public void setLiveStatus(Integer liveStatus) {
        this.liveStatus = liveStatus;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Integer getResourceType() {
        return resourceType;
    }

    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public String getTeacherAvatar() {
        return teacherAvatar;
    }

    public void setTeacherAvatar(String teacherAvatar) {
        this.teacherAvatar = teacherAvatar;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
