package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CourseBean.
 */
public class CourseBean implements java.io.Serializable {

    private Long id;
    private Long CourseId;
    private Long createOn;
    private Long updateOn;
    private Long teacherId;
    private String teacherName;
    private Long labelId;
    private String labelName;
    private Integer type;
    private String title;
    private String description;
    private String cover;
    private Integer status;
    private Long hits;
    private Double score;
    private Long scoreCnt;
    private Long startOn;
    private Long endOn;
    private String teacherDesc;
    private String teacherAvatar;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CourseBean() {
    }

    public CourseBean(Long id) {
        this.id = id;
    }

    public CourseBean(Long id, Long CourseId, Long createOn, Long updateOn, Long teacherId, String teacherName, Long labelId, String labelName, Integer type, String title, String description, String cover, Integer status, Long hits, Double score, Long scoreCnt, Long startOn, Long endOn, String teacherDesc, String teacherAvatar) {
        this.id = id;
        this.CourseId = CourseId;
        this.createOn = createOn;
        this.updateOn = updateOn;
        this.teacherId = teacherId;
        this.teacherName = teacherName;
        this.labelId = labelId;
        this.labelName = labelName;
        this.type = type;
        this.title = title;
        this.description = description;
        this.cover = cover;
        this.status = status;
        this.hits = hits;
        this.score = score;
        this.scoreCnt = scoreCnt;
        this.startOn = startOn;
        this.endOn = endOn;
        this.teacherDesc = teacherDesc;
        this.teacherAvatar = teacherAvatar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCourseId() {
        return CourseId;
    }

    public void setCourseId(Long CourseId) {
        this.CourseId = CourseId;
    }

    public Long getCreateOn() {
        return createOn;
    }

    public void setCreateOn(Long createOn) {
        this.createOn = createOn;
    }

    public Long getUpdateOn() {
        return updateOn;
    }

    public void setUpdateOn(Long updateOn) {
        this.updateOn = updateOn;
    }

    public Long getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public Long getLabelId() {
        return labelId;
    }

    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    public String getLabelName() {
        return labelName;
    }

    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getHits() {
        return hits;
    }

    public void setHits(Long hits) {
        this.hits = hits;
    }

    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

    public Long getScoreCnt() {
        return scoreCnt;
    }

    public void setScoreCnt(Long scoreCnt) {
        this.scoreCnt = scoreCnt;
    }

    public Long getStartOn() {
        return startOn;
    }

    public void setStartOn(Long startOn) {
        this.startOn = startOn;
    }

    public Long getEndOn() {
        return endOn;
    }

    public void setEndOn(Long endOn) {
        this.endOn = endOn;
    }

    public String getTeacherDesc() {
        return teacherDesc;
    }

    public void setTeacherDesc(String teacherDesc) {
        this.teacherDesc = teacherDesc;
    }

    public String getTeacherAvatar() {
        return teacherAvatar;
    }

    public void setTeacherAvatar(String teacherAvatar) {
        this.teacherAvatar = teacherAvatar;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
