package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblDataReport.
 */
public class DataReport implements java.io.Serializable {

    private Long id;
    private long userId;
    private int eventType;
    private String bid;
    private long timestamp;
    private boolean isSended;
    private Long serialNo;
    private String extendedInfo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DataReport() {
    }

    public DataReport(Long id) {
        this.id = id;
    }

    public DataReport(Long id, long userId, int eventType, String bid, long timestamp, boolean isSended, Long serialNo, String extendedInfo) {
        this.id = id;
        this.userId = userId;
        this.eventType = eventType;
        this.bid = bid;
        this.timestamp = timestamp;
        this.isSended = isSended;
        this.serialNo = serialNo;
        this.extendedInfo = extendedInfo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getEventType() {
        return eventType;
    }

    public void setEventType(int eventType) {
        this.eventType = eventType;
    }

    public String getBid() {
        return bid;
    }

    public void setBid(String bid) {
        this.bid = bid;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public boolean getIsSended() {
        return isSended;
    }

    public void setIsSended(boolean isSended) {
        this.isSended = isSended;
    }

    public Long getSerialNo() {
        return serialNo;
    }

    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    public String getExtendedInfo() {
        return extendedInfo;
    }

    public void setExtendedInfo(String extendedInfo) {
        this.extendedInfo = extendedInfo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
