package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table department_user.
 */
public class DepartmentUser implements java.io.Serializable {

    private Long id;
    private long userId;
    private long departmentId;
    private Integer role;
    private Boolean admin;
    private Integer gagSetting;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DepartmentUser() {
    }

    public DepartmentUser(Long id) {
        this.id = id;
    }

    public DepartmentUser(Long id, long userId, long departmentId, Integer role, Boolean admin, Integer gagSetting) {
        this.id = id;
        this.userId = userId;
        this.departmentId = departmentId;
        this.role = role;
        this.admin = admin;
        this.gagSetting = gagSetting;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(long departmentId) {
        this.departmentId = departmentId;
    }

    public Integer getRole() {
        return role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public Boolean getAdmin() {
        return admin;
    }

    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    public Integer getGagSetting() {
        return gagSetting;
    }

    public void setGagSetting(Integer gagSetting) {
        this.gagSetting = gagSetting;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
