package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table department.
 */
public class Department implements java.io.Serializable {

    private Long id;
    private long departmentId;
    /** Not-null value. */
    private String name;
    private String avatar;
    private Boolean showParents;
    private Long parentId;
    private Integer type;
    private String chatGroupId;
    private Long lastSync;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Department() {
    }

    public Department(Long id) {
        this.id = id;
    }

    public Department(Long id, long departmentId, String name, String avatar, Boolean showParents, Long parentId, Integer type, String chatGroupId, Long lastSync) {
        this.id = id;
        this.departmentId = departmentId;
        this.name = name;
        this.avatar = avatar;
        this.showParents = showParents;
        this.parentId = parentId;
        this.type = type;
        this.chatGroupId = chatGroupId;
        this.lastSync = lastSync;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(long departmentId) {
        this.departmentId = departmentId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Boolean getShowParents() {
        return showParents;
    }

    public void setShowParents(Boolean showParents) {
        this.showParents = showParents;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getChatGroupId() {
        return chatGroupId;
    }

    public void setChatGroupId(String chatGroupId) {
        this.chatGroupId = chatGroupId;
    }

    public Long getLastSync() {
        return lastSync;
    }

    public void setLastSync(Long lastSync) {
        this.lastSync = lastSync;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
