package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table feed.
 */
public class Feed implements java.io.Serializable {

    private Long id;
    private long feedId;
    private String content;
    private String attachments;
    private Long userId;
    private String userName;
    private String userAvatar;
    private Integer userType;
    private Integer feedType;
    private Long publishTime;
    private Boolean hasMoreComment;

    // KEEP FIELDS - put your custom fields here
    Long ActivityId;
    List<Comment> comments;
    List<Comment> likes;
    // KEEP FIELDS END

    public Feed() {
    }

    public Feed(Long id) {
        this.id = id;
    }

    public Feed(Long id, long feedId, String content, String attachments, Long userId, String userName, String userAvatar, Integer userType, Integer feedType, Long publishTime, Boolean hasMoreComment) {
        this.id = id;
        this.feedId = feedId;
        this.content = content;
        this.attachments = attachments;
        this.userId = userId;
        this.userName = userName;
        this.userAvatar = userAvatar;
        this.userType = userType;
        this.feedType = feedType;
        this.publishTime = publishTime;
        this.hasMoreComment = hasMoreComment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getFeedId() {
        return feedId;
    }

    public void setFeedId(long feedId) {
        this.feedId = feedId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAttachments() {
        return attachments;
    }

    public void setAttachments(String attachments) {
        this.attachments = attachments;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserAvatar() {
        return userAvatar;
    }

    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }

    public Integer getUserType() {
        return userType;
    }

    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    public Integer getFeedType() {
        return feedType;
    }

    public void setFeedType(Integer feedType) {
        this.feedType = feedType;
    }

    public Long getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    public Boolean getHasMoreComment() {
        return hasMoreComment;
    }

    public void setHasMoreComment(Boolean hasMoreComment) {
        this.hasMoreComment = hasMoreComment;
    }

    // KEEP METHODS - put your custom methods here

    public Long getActivityId() {
        return ActivityId;
    }

    public void setActivityId(Long activityId) {
        ActivityId = activityId;
    }

    public List<Comment> getComments() {
        return comments;
    }

    public void setComments(List<Comment> comments) {
        this.comments = comments;
    }

    public List<Comment> getLikes() {
        return likes;
    }

    public void setLikes(List<Comment> likes) {
        this.likes = likes;
    }
    // KEEP METHODS END

}
