package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table Game_Score.
 */
public class Game_Score implements java.io.Serializable {

    private Long id;
    private String gameName;
    private Integer score;
    private Integer bestLevel;
    private Double percentage;
    private String color;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Game_Score() {
    }

    public Game_Score(Long id) {
        this.id = id;
    }

    public Game_Score(Long id, String gameName, Integer score, Integer bestLevel, Double percentage, String color) {
        this.id = id;
        this.gameName = gameName;
        this.score = score;
        this.bestLevel = bestLevel;
        this.percentage = percentage;
        this.color = color;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getBestLevel() {
        return bestLevel;
    }

    public void setBestLevel(Integer bestLevel) {
        this.bestLevel = bestLevel;
    }

    public Double getPercentage() {
        return percentage;
    }

    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
