package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GameLevel.
 */
public class GameLevel implements java.io.Serializable {

    private Long id;
    private Long gameId;
    private Integer level;
    private String gameName;
    private String abilityName;
    private String picUrl;
    private Integer stars;
    private String color;
    private String choicelevel;
    private Boolean hasGuide;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GameLevel() {
    }

    public GameLevel(Long id) {
        this.id = id;
    }

    public GameLevel(Long id, Long gameId, Integer level, String gameName, String abilityName, String picUrl, Integer stars, String color, String choicelevel, Boolean hasGuide) {
        this.id = id;
        this.gameId = gameId;
        this.level = level;
        this.gameName = gameName;
        this.abilityName = abilityName;
        this.picUrl = picUrl;
        this.stars = stars;
        this.color = color;
        this.choicelevel = choicelevel;
        this.hasGuide = hasGuide;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGameId() {
        return gameId;
    }

    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getAbilityName() {
        return abilityName;
    }

    public void setAbilityName(String abilityName) {
        this.abilityName = abilityName;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public Integer getStars() {
        return stars;
    }

    public void setStars(Integer stars) {
        this.stars = stars;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getChoicelevel() {
        return choicelevel;
    }

    public void setChoicelevel(String choicelevel) {
        this.choicelevel = choicelevel;
    }

    public Boolean getHasGuide() {
        return hasGuide;
    }

    public void setHasGuide(Boolean hasGuide) {
        this.hasGuide = hasGuide;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
