package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HomeWorkMember.
 */
public class HomeWorkMember implements java.io.Serializable {

    private Long id;
    private Long memberId;
    private String name;
    private String avatar;
    private Integer status;
    private Integer score;
    private Boolean specialAttention;
    private Long homeworkId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HomeWorkMember() {
    }

    public HomeWorkMember(Long id) {
        this.id = id;
    }

    public HomeWorkMember(Long id, Long memberId, String name, String avatar, Integer status, Integer score, Boolean specialAttention, Long homeworkId) {
        this.id = id;
        this.memberId = memberId;
        this.name = name;
        this.avatar = avatar;
        this.status = status;
        this.score = score;
        this.specialAttention = specialAttention;
        this.homeworkId = homeworkId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Boolean getSpecialAttention() {
        return specialAttention;
    }

    public void setSpecialAttention(Boolean specialAttention) {
        this.specialAttention = specialAttention;
    }

    public Long getHomeworkId() {
        return homeworkId;
    }

    public void setHomeworkId(Long homeworkId) {
        this.homeworkId = homeworkId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
