package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HomeWorkGenerate.
 */
public class HomeWorkGenerate implements java.io.Serializable {

    private Long id;
    private Long childUserId;
    private String name;
    private String avatar;
    private Integer generateCount;
    private Integer remainMaxCount;
    private Boolean specialAttention;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HomeWorkGenerate() {
    }

    public HomeWorkGenerate(Long id) {
        this.id = id;
    }

    public HomeWorkGenerate(Long id, Long childUserId, String name, String avatar, Integer generateCount, Integer remainMaxCount, Boolean specialAttention) {
        this.id = id;
        this.childUserId = childUserId;
        this.name = name;
        this.avatar = avatar;
        this.generateCount = generateCount;
        this.remainMaxCount = remainMaxCount;
        this.specialAttention = specialAttention;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getChildUserId() {
        return childUserId;
    }

    public void setChildUserId(Long childUserId) {
        this.childUserId = childUserId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getGenerateCount() {
        return generateCount;
    }

    public void setGenerateCount(Integer generateCount) {
        this.generateCount = generateCount;
    }

    public Integer getRemainMaxCount() {
        return remainMaxCount;
    }

    public void setRemainMaxCount(Integer remainMaxCount) {
        this.remainMaxCount = remainMaxCount;
    }

    public Boolean getSpecialAttention() {
        return specialAttention;
    }

    public void setSpecialAttention(Boolean specialAttention) {
        this.specialAttention = specialAttention;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
