package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HomeWorkDetail.
 */
public class HomeWorkDetail implements java.io.Serializable {

    private Long id;
    private Long memberId;
    private Integer status;
    private String title;
    private String description;
    private String senderName;
    private Integer totalScore;
    private Integer maxScore;
    private Long sendTime;
    private Long childUserId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HomeWorkDetail() {
    }

    public HomeWorkDetail(Long id) {
        this.id = id;
    }

    public HomeWorkDetail(Long id, Long memberId, Integer status, String title, String description, String senderName, Integer totalScore, Integer maxScore, Long sendTime, Long childUserId) {
        this.id = id;
        this.memberId = memberId;
        this.status = status;
        this.title = title;
        this.description = description;
        this.senderName = senderName;
        this.totalScore = totalScore;
        this.maxScore = maxScore;
        this.sendTime = sendTime;
        this.childUserId = childUserId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSenderName() {
        return senderName;
    }

    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public Integer getTotalScore() {
        return totalScore;
    }

    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    public Integer getMaxScore() {
        return maxScore;
    }

    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    public Long getSendTime() {
        return sendTime;
    }

    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }

    public Long getChildUserId() {
        return childUserId;
    }

    public void setChildUserId(Long childUserId) {
        this.childUserId = childUserId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
