package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HomeWorkUserRank.
 */
public class HomeWorkUserRank implements java.io.Serializable {

    private Long id;
    private Integer rank;
    private Long userId;
    private String name;
    private String avatar;
    private Integer score;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HomeWorkUserRank() {
    }

    public HomeWorkUserRank(Long id) {
        this.id = id;
    }

    public HomeWorkUserRank(Long id, Integer rank, Long userId, String name, String avatar, Integer score) {
        this.id = id;
        this.rank = rank;
        this.userId = userId;
        this.name = name;
        this.avatar = avatar;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
