package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HomeWorkClass.
 */
public class HomeWorkClass implements java.io.Serializable {

    private Long id;
    private Long homeworkId;
    private String className;
    private String title;
    private Integer type;
    private Long sendTime;
    private Integer finishedCount;
    private Integer totalCount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HomeWorkClass() {
    }

    public HomeWorkClass(Long id) {
        this.id = id;
    }

    public HomeWorkClass(Long id, Long homeworkId, String className, String title, Integer type, Long sendTime, Integer finishedCount, Integer totalCount) {
        this.id = id;
        this.homeworkId = homeworkId;
        this.className = className;
        this.title = title;
        this.type = type;
        this.sendTime = sendTime;
        this.finishedCount = finishedCount;
        this.totalCount = totalCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getHomeworkId() {
        return homeworkId;
    }

    public void setHomeworkId(Long homeworkId) {
        this.homeworkId = homeworkId;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getSendTime() {
        return sendTime;
    }

    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }

    public Integer getFinishedCount() {
        return finishedCount;
    }

    public void setFinishedCount(Integer finishedCount) {
        this.finishedCount = finishedCount;
    }

    public Integer getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
