package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table login_user.
 */
public class LoginUser implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String token;
    private long userId;
    /** Not-null value. */
    private String username;
    private String password;
    private boolean active;
    private int status;
    private Long lastLoginTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LoginUser() {
    }

    public LoginUser(Long id) {
        this.id = id;
    }

    public LoginUser(Long id, String token, long userId, String username, String password, boolean active, int status, Long lastLoginTime) {
        this.id = id;
        this.token = token;
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.active = active;
        this.status = status;
        this.lastLoginTime = lastLoginTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(String token) {
        this.token = token;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean getActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
