package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table notice.
 */
public class Notice implements java.io.Serializable {

    private Long id;
    private long noticeId;
    private Long senderUserId;
    private String senderName;
    private String senderAvatar;
    private String summary;
    private Boolean unread;
    private String content;
    private String attachments;
    private Long sendTime;
    private int mailbox;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Notice() {
    }

    public Notice(Long id) {
        this.id = id;
    }

    public Notice(Long id, long noticeId, Long senderUserId, String senderName, String senderAvatar, String summary, Boolean unread, String content, String attachments, Long sendTime, int mailbox) {
        this.id = id;
        this.noticeId = noticeId;
        this.senderUserId = senderUserId;
        this.senderName = senderName;
        this.senderAvatar = senderAvatar;
        this.summary = summary;
        this.unread = unread;
        this.content = content;
        this.attachments = attachments;
        this.sendTime = sendTime;
        this.mailbox = mailbox;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getNoticeId() {
        return noticeId;
    }

    public void setNoticeId(long noticeId) {
        this.noticeId = noticeId;
    }

    public Long getSenderUserId() {
        return senderUserId;
    }

    public void setSenderUserId(Long senderUserId) {
        this.senderUserId = senderUserId;
    }

    public String getSenderName() {
        return senderName;
    }

    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public String getSenderAvatar() {
        return senderAvatar;
    }

    public void setSenderAvatar(String senderAvatar) {
        this.senderAvatar = senderAvatar;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Boolean getUnread() {
        return unread;
    }

    public void setUnread(Boolean unread) {
        this.unread = unread;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAttachments() {
        return attachments;
    }

    public void setAttachments(String attachments) {
        this.attachments = attachments;
    }

    public Long getSendTime() {
        return sendTime;
    }

    public void setSendTime(Long sendTime) {
        this.sendTime = sendTime;
    }

    public int getMailbox() {
        return mailbox;
    }

    public void setMailbox(int mailbox) {
        this.mailbox = mailbox;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
