package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ScoreShow.
 */
public class ScoreShow implements java.io.Serializable {

    private Long id;
    private Integer totalAbilityLevel;
    private Double totalAbilityPercentage;
    private Integer abilityQuotient;
    private Integer maxAbilityQuotient;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ScoreShow() {
    }

    public ScoreShow(Long id) {
        this.id = id;
    }

    public ScoreShow(Long id, Integer totalAbilityLevel, Double totalAbilityPercentage, Integer abilityQuotient, Integer maxAbilityQuotient) {
        this.id = id;
        this.totalAbilityLevel = totalAbilityLevel;
        this.totalAbilityPercentage = totalAbilityPercentage;
        this.abilityQuotient = abilityQuotient;
        this.maxAbilityQuotient = maxAbilityQuotient;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTotalAbilityLevel() {
        return totalAbilityLevel;
    }

    public void setTotalAbilityLevel(Integer totalAbilityLevel) {
        this.totalAbilityLevel = totalAbilityLevel;
    }

    public Double getTotalAbilityPercentage() {
        return totalAbilityPercentage;
    }

    public void setTotalAbilityPercentage(Double totalAbilityPercentage) {
        this.totalAbilityPercentage = totalAbilityPercentage;
    }

    public Integer getAbilityQuotient() {
        return abilityQuotient;
    }

    public void setAbilityQuotient(Integer abilityQuotient) {
        this.abilityQuotient = abilityQuotient;
    }

    public Integer getMaxAbilityQuotient() {
        return maxAbilityQuotient;
    }

    public void setMaxAbilityQuotient(Integer maxAbilityQuotient) {
        this.maxAbilityQuotient = maxAbilityQuotient;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
