package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table setting.
 */
public class Setting implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String field;
    private String value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Setting() {
    }

    public Setting(Long id) {
        this.id = id;
    }

    public Setting(Long id, String field, String value) {
        this.id = id;
        this.field = field;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getField() {
        return field;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setField(String field) {
        this.field = field;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
