package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TestList.
 */
public class TestList implements java.io.Serializable {

    private Long id;
    private String name;
    private String description;
    private String associateTag;
    private Integer color;
    private String colorValue;
    private Integer status;
    private String animalPic;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TestList() {
    }

    public TestList(Long id) {
        this.id = id;
    }

    public TestList(Long id, String name, String description, String associateTag, Integer color, String colorValue, Integer status, String animalPic) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.associateTag = associateTag;
        this.color = color;
        this.colorValue = colorValue;
        this.status = status;
        this.animalPic = animalPic;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAssociateTag() {
        return associateTag;
    }

    public void setAssociateTag(String associateTag) {
        this.associateTag = associateTag;
    }

    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public String getColorValue() {
        return colorValue;
    }

    public void setColorValue(String colorValue) {
        this.colorValue = colorValue;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getAnimalPic() {
        return animalPic;
    }

    public void setAnimalPic(String animalPic) {
        this.animalPic = animalPic;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
