package com.tuxing.sdk.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table user.
 */
public class User implements java.io.Serializable {

    private Long id;
    private long userId;
    /** Not-null value. */
    private String username;
    private int type;
    private String nickname;
    private String realname;
    private String mobile;
    private Long birthday;
    private String address;
    private Integer gender;
    private Long positionId;
    private String positionName;
    private Integer disturbedFreeSetting;
    private String avatar;
    private Long childUserId;
    private String signature;
    private String className;
    private String gardenName;
    private Integer relativeType;
    private Long gardenId;
    private Long classId;
    private String guarder;
    private Boolean activated;
    private String combinedNickname;

    // KEEP FIELDS - put your custom fields here
    private String password;
    private boolean active;
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, long userId, String username, int type, String nickname, String realname, String mobile, Long birthday, String address, Integer gender, Long positionId, String positionName, Integer disturbedFreeSetting, String avatar, Long childUserId, String signature, String className, String gardenName, Integer relativeType, Long gardenId, Long classId, String guarder, Boolean activated, String combinedNickname) {
        this.id = id;
        this.userId = userId;
        this.username = username;
        this.type = type;
        this.nickname = nickname;
        this.realname = realname;
        this.mobile = mobile;
        this.birthday = birthday;
        this.address = address;
        this.gender = gender;
        this.positionId = positionId;
        this.positionName = positionName;
        this.disturbedFreeSetting = disturbedFreeSetting;
        this.avatar = avatar;
        this.childUserId = childUserId;
        this.signature = signature;
        this.className = className;
        this.gardenName = gardenName;
        this.relativeType = relativeType;
        this.gardenId = gardenId;
        this.classId = classId;
        this.guarder = guarder;
        this.activated = activated;
        this.combinedNickname = combinedNickname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Long getPositionId() {
        return positionId;
    }

    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public Integer getDisturbedFreeSetting() {
        return disturbedFreeSetting;
    }

    public void setDisturbedFreeSetting(Integer disturbedFreeSetting) {
        this.disturbedFreeSetting = disturbedFreeSetting;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Long getChildUserId() {
        return childUserId;
    }

    public void setChildUserId(Long childUserId) {
        this.childUserId = childUserId;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getGardenName() {
        return gardenName;
    }

    public void setGardenName(String gardenName) {
        this.gardenName = gardenName;
    }

    public Integer getRelativeType() {
        return relativeType;
    }

    public void setRelativeType(Integer relativeType) {
        this.relativeType = relativeType;
    }

    public Long getGardenId() {
        return gardenId;
    }

    public void setGardenId(Long gardenId) {
        this.gardenId = gardenId;
    }

    public Long getClassId() {
        return classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public String getGuarder() {
        return guarder;
    }

    public void setGuarder(String guarder) {
        this.guarder = guarder;
    }

    public Boolean getActivated() {
        return activated;
    }

    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    public String getCombinedNickname() {
        return combinedNickname;
    }

    public void setCombinedNickname(String combinedNickname) {
        this.combinedNickname = combinedNickname;
    }

    // KEEP METHODS - put your custom methods here

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
    // KEEP METHODS END

}
