// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/LearningAbility.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 原生新接口 用户学习能力统计
 * URL:/learning_ability
 */
public final class AbilityStatRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_CHILDUSERID = 0L;

  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long childUserId;

  public AbilityStatRequest(Long childUserId) {
    this.childUserId = childUserId;
  }

  private AbilityStatRequest(Builder builder) {
    this(builder.childUserId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AbilityStatRequest)) return false;
    return equals(childUserId, ((AbilityStatRequest) other).childUserId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = childUserId != null ? childUserId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<AbilityStatRequest> {

    public Long childUserId;

    public Builder() {
    }

    public Builder(AbilityStatRequest message) {
      super(message);
      if (message == null) return;
      this.childUserId = message.childUserId;
    }

    public Builder childUserId(Long childUserId) {
      this.childUserId = childUserId;
      return this;
    }

    @Override
    public AbilityStatRequest build() {
      checkRequiredFields();
      return new AbilityStatRequest(this);
    }
  }
}
