// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;

public final class DeleteHomeworkNoticeResponse extends Message {
  private static final long serialVersionUID = 0L;

  public DeleteHomeworkNoticeResponse() {
  }

  private DeleteHomeworkNoticeResponse(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof DeleteHomeworkNoticeResponse;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<DeleteHomeworkNoticeResponse> {

    public Builder() {
    }

    public Builder(DeleteHomeworkNoticeResponse message) {
      super(message);
    }

    @Override
    public DeleteHomeworkNoticeResponse build() {
      return new DeleteHomeworkNoticeResponse(this);
    }
  }
}
