// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 删除作业通知
 * URL:/homework/delete_notice
 */
public final class DeleteHomeworkNoticeRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_HOMEWORKNOTICEID = 0L;

  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long homeworkNoticeId;

  public DeleteHomeworkNoticeRequest(Long homeworkNoticeId) {
    this.homeworkNoticeId = homeworkNoticeId;
  }

  private DeleteHomeworkNoticeRequest(Builder builder) {
    this(builder.homeworkNoticeId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DeleteHomeworkNoticeRequest)) return false;
    return equals(homeworkNoticeId, ((DeleteHomeworkNoticeRequest) other).homeworkNoticeId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = homeworkNoticeId != null ? homeworkNoticeId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<DeleteHomeworkNoticeRequest> {

    public Long homeworkNoticeId;

    public Builder() {
    }

    public Builder(DeleteHomeworkNoticeRequest message) {
      super(message);
      if (message == null) return;
      this.homeworkNoticeId = message.homeworkNoticeId;
    }

    public Builder homeworkNoticeId(Long homeworkNoticeId) {
      this.homeworkNoticeId = homeworkNoticeId;
      return this;
    }

    @Override
    public DeleteHomeworkNoticeRequest build() {
      checkRequiredFields();
      return new DeleteHomeworkNoticeRequest(this);
    }
  }
}
