// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Data.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.ProtoEnum;

public enum EventType
    implements ProtoEnum {
  /**
   * type		bid类型
   * APP登陆		不需要
   */
  APP_LOGIN(1),
  /**
   * APP登出		不需要
   */
  APP_LOGOUT(2),
  /**
   * 功能模块进入	channelId(模块ID)
   */
  CHANNEL_IN(3),
  /**
   * 功能模块退出	channelId
   */
  CHANNEL_OUT(4),
  /**
   * 进入游戏		gameId
   */
  GAME_IN(5),
  /**
   * 退出游戏		gameId
   */
  GAME_OUT(6),
  /**
   * 进入课程		lessonId
   */
  LESSON_IN(7),
  /**
   * 退出课程		lessonId
   */
  LESSON_OUT(8),
  /**
   * 点击文章		articleId
   */
  ARTICLE_IN(9),
  /**
   * 退出文章		articleId
   */
  ARTICLE_OUT(10),
  /**
   * 单聊		toPid
   */
  SINGLE_CHAT(11),
  /**
   * 群聊		groupId
   */
  GROUP_CHAT(12),
  /**
   * 教师群聊	groupId
   */
  TEACHER_GROUP_CHAT(13);

  private final int value;

  EventType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
