// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Game.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;

/**
 * 获取游戏列表
 * URL:/game/list
 */
public final class GameListRequest extends Message {
  private static final long serialVersionUID = 0L;

  public GameListRequest() {
  }

  private GameListRequest(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof GameListRequest;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<GameListRequest> {

    public Builder() {
    }

    public Builder(GameListRequest message) {
      super(message);
    }

    @Override
    public GameListRequest build() {
      return new GameListRequest(this);
    }
  }
}
