// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Label.REPEATED;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class HomeworkListResponse extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<Homework> DEFAULT_HOMEWORKS = Collections.emptyList();
  public static final Boolean DEFAULT_HASMORE = false;

  @ProtoField(tag = 1, label = REPEATED, messageType = Homework.class)
  public final List<Homework> homeworks;

  @ProtoField(tag = 2, type = BOOL, label = REQUIRED)
  public final Boolean hasMore;

  public HomeworkListResponse(List<Homework> homeworks, Boolean hasMore) {
    this.homeworks = immutableCopyOf(homeworks);
    this.hasMore = hasMore;
  }

  private HomeworkListResponse(Builder builder) {
    this(builder.homeworks, builder.hasMore);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HomeworkListResponse)) return false;
    HomeworkListResponse o = (HomeworkListResponse) other;
    return equals(homeworks, o.homeworks)
        && equals(hasMore, o.hasMore);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = homeworks != null ? homeworks.hashCode() : 1;
      result = result * 37 + (hasMore != null ? hasMore.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<HomeworkListResponse> {

    public List<Homework> homeworks;
    public Boolean hasMore;

    public Builder() {
    }

    public Builder(HomeworkListResponse message) {
      super(message);
      if (message == null) return;
      this.homeworks = copyOf(message.homeworks);
      this.hasMore = message.hasMore;
    }

    public Builder homeworks(List<Homework> homeworks) {
      this.homeworks = checkForNulls(homeworks);
      return this;
    }

    public Builder hasMore(Boolean hasMore) {
      this.hasMore = hasMore;
      return this;
    }

    @Override
    public HomeworkListResponse build() {
      checkRequiredFields();
      return new HomeworkListResponse(this);
    }
  }
}
