// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.ProtoEnum;

public enum HomeworkStatus
    implements ProtoEnum {
  UNFINISHED(0),
  FINISHED(1);

  private final int value;

  HomeworkStatus(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
