// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class HomeworkRemainingCountResponse extends Message {
  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_CUSTOMIZEDSTATUS = false;
  public static final Integer DEFAULT_UNIFIEDCOUNT = 0;

  /**
   * 定制作业是否可以发送
   */
  @ProtoField(tag = 1, type = BOOL, label = REQUIRED)
  public final Boolean customizedStatus;

  /**
   * 统一作业剩余数量
   */
  @ProtoField(tag = 2, type = INT32, label = REQUIRED)
  public final Integer unifiedCount;

  public HomeworkRemainingCountResponse(Boolean customizedStatus, Integer unifiedCount) {
    this.customizedStatus = customizedStatus;
    this.unifiedCount = unifiedCount;
  }

  private HomeworkRemainingCountResponse(Builder builder) {
    this(builder.customizedStatus, builder.unifiedCount);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HomeworkRemainingCountResponse)) return false;
    HomeworkRemainingCountResponse o = (HomeworkRemainingCountResponse) other;
    return equals(customizedStatus, o.customizedStatus)
        && equals(unifiedCount, o.unifiedCount);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = customizedStatus != null ? customizedStatus.hashCode() : 0;
      result = result * 37 + (unifiedCount != null ? unifiedCount.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<HomeworkRemainingCountResponse> {

    public Boolean customizedStatus;
    public Integer unifiedCount;

    public Builder() {
    }

    public Builder(HomeworkRemainingCountResponse message) {
      super(message);
      if (message == null) return;
      this.customizedStatus = message.customizedStatus;
      this.unifiedCount = message.unifiedCount;
    }

    /**
     * 定制作业是否可以发送
     */
    public Builder customizedStatus(Boolean customizedStatus) {
      this.customizedStatus = customizedStatus;
      return this;
    }

    /**
     * 统一作业剩余数量
     */
    public Builder unifiedCount(Integer unifiedCount) {
      this.unifiedCount = unifiedCount;
      return this;
    }

    @Override
    public HomeworkRemainingCountResponse build() {
      checkRequiredFields();
      return new HomeworkRemainingCountResponse(this);
    }
  }
}
