// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.ProtoEnum;

public enum HomeworkType
    implements ProtoEnum {
  /**
   * 定制作业
   */
  CUSTOMIZED(1),
  /**
   * 统一作业
   */
  UNIFIED(2);

  private final int value;

  HomeworkType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
