// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 获取本月作业情况统计月历
 * URL:/homework/calendar
 */
public final class HomeworkCalendarRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_CHILDUSERID = 0L;

  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long childUserId;

  public HomeworkCalendarRequest(Long childUserId) {
    this.childUserId = childUserId;
  }

  private HomeworkCalendarRequest(Builder builder) {
    this(builder.childUserId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HomeworkCalendarRequest)) return false;
    return equals(childUserId, ((HomeworkCalendarRequest) other).childUserId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = childUserId != null ? childUserId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<HomeworkCalendarRequest> {

    public Long childUserId;

    public Builder() {
    }

    public Builder(HomeworkCalendarRequest message) {
      super(message);
      if (message == null) return;
      this.childUserId = message.childUserId;
    }

    public Builder childUserId(Long childUserId) {
      this.childUserId = childUserId;
      return this;
    }

    @Override
    public HomeworkCalendarRequest build() {
      checkRequiredFields();
      return new HomeworkCalendarRequest(this);
    }
  }
}
