// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 生成作业详情
 * URL:/homework/generate_detail
 */
public final class HomeworkGenerateDetailRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_CLASSID = 0L;
  public static final Long DEFAULT_CHILDUSERID = 0L;

  /**
   * 班级ID
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long classId;

  /**
   * 孩子ID
   */
  @ProtoField(tag = 2, type = INT64, label = REQUIRED)
  public final Long childUserId;

  public HomeworkGenerateDetailRequest(Long classId, Long childUserId) {
    this.classId = classId;
    this.childUserId = childUserId;
  }

  private HomeworkGenerateDetailRequest(Builder builder) {
    this(builder.classId, builder.childUserId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HomeworkGenerateDetailRequest)) return false;
    HomeworkGenerateDetailRequest o = (HomeworkGenerateDetailRequest) other;
    return equals(classId, o.classId)
        && equals(childUserId, o.childUserId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = classId != null ? classId.hashCode() : 0;
      result = result * 37 + (childUserId != null ? childUserId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<HomeworkGenerateDetailRequest> {

    public Long classId;
    public Long childUserId;

    public Builder() {
    }

    public Builder(HomeworkGenerateDetailRequest message) {
      super(message);
      if (message == null) return;
      this.classId = message.classId;
      this.childUserId = message.childUserId;
    }

    /**
     * 班级ID
     */
    public Builder classId(Long classId) {
      this.classId = classId;
      return this;
    }

    /**
     * 孩子ID
     */
    public Builder childUserId(Long childUserId) {
      this.childUserId = childUserId;
      return this;
    }

    @Override
    public HomeworkGenerateDetailRequest build() {
      checkRequiredFields();
      return new HomeworkGenerateDetailRequest(this);
    }
  }
}
