// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/resources/proto/Homework.proto
package com.xcsd.rpc.proto;

import com.squareup.wire.ProtoEnum;

public enum StudentScope
    implements ProtoEnum {
  ALL(1),
  NORMAL(2),
  SPECIAL(3);

  private final int value;

  StudentScope(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
